name: health_app
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  intl: 0.17.0
  json_path: 0.4.1
  lottie: 1.2.1
  page_transition: 2.0.4
  percent_indicator: 4.2.2
  shared_preferences: 2.0.15
  timeago: 3.2.2
  url_launcher: 6.1.5


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
